# Generated by Django 5.0 on 2024-02-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_learning_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quartet',
            name='frame',
            field=models.BooleanField(default=False, verbose_name='枠'),
        ),
    ]
