# Generated by Django 5.0 on 2024-02-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_learning_app', '0003_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='quartet',
            name='primary_key',
            field=models.PositiveIntegerField(default=1, verbose_name='primary_key'),
        ),
    ]
