# Generated by Django 5.0 on 2024-02-21 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_learning_app', '0005_remove_quartet_id_alter_quartet_primary_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuartetResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(verbose_name='ユーザーID')),
                ('result', models.BooleanField(verbose_name='結果')),
                ('connection_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='python_learning_app.quartet')),
            ],
        ),
    ]
