# Generated by Django 4.2.7 on 2023-12-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonL', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basis',
            name='c_output',
            field=models.TextField(blank=True, verbose_name='要求出力/nct/改'),
        ),
        migrations.AlterField(
            model_name='basis',
            name='e_answer',
            field=models.TextField(blank=True, verbose_name='解答例/nct//mrcl/'),
        ),
        migrations.AlterField(
            model_name='basis',
            name='q_data',
            field=models.TextField(blank=True, verbose_name='出題データ/nct/bbcl/'),
        ),
    ]
