# Generated by Django 4.2.7 on 2023-12-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonL', '0002_alter_basis_c_output_alter_basis_e_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basis',
            name='e_answer',
            field=models.TextField(blank=True, verbose_name='解答例/nct/mrcl/'),
        ),
    ]
