# Generated by Django 4.2.7 on 2023-12-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonL', '0005_alter_basis_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='basis',
            name='post_visual',
            field=models.TextField(blank=True, verbose_name='入力視像（後）'),
        ),
        migrations.AddField(
            model_name='basis',
            name='pre_visual',
            field=models.TextField(blank=True, verbose_name='入力視像（前）'),
        ),
    ]
