# Generated by Django 4.2.7 on 2023-12-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonL', '0006_basis_post_visual_basis_pre_visual'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntroCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='題名')),
                ('title', models.CharField(max_length=60, verbose_name='タイトル')),
                ('section', models.PositiveSmallIntegerField(verbose_name='表示順')),
                ('content', models.TextField(blank=True, verbose_name='内容')),
            ],
        ),
        migrations.AlterField(
            model_name='basis',
            name='name',
            field=models.CharField(max_length=80, verbose_name='題名'),
        ),
        migrations.AlterField(
            model_name='basis',
            name='title',
            field=models.CharField(max_length=60, verbose_name='問題名'),
        ),
    ]
