# Generated by Django 4.2.7 on 2023-12-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonL', '0007_introcourse_alter_basis_name_alter_basis_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='introcourse',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='順番'),
        ),
        migrations.AlterField(
            model_name='introcourse',
            name='section',
            field=models.PositiveIntegerField(verbose_name='区分'),
        ),
    ]
