# Generated by Django 4.2.7 on 2023-12-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonL', '0008_introcourse_order_alter_introcourse_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='introcourse',
            name='title',
        ),
        migrations.AddField(
            model_name='introcourse',
            name='text_type',
            field=models.CharField(blank=True, choices=[('heading', '見出し'), ('text', 'テキスト'), ('red', '赤枠'), ('yellow', '黄枠'), ('blue', '青枠'), ('green', '緑枠')], max_length=20, verbose_name='タイプ'),
        ),
    ]
