# Generated by Django 4.2.7 on 2023-12-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonL', '0009_remove_introcourse_title_introcourse_text_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='introcourse',
            name='name',
        ),
        migrations.AddField(
            model_name='introcourse',
            name='title',
            field=models.CharField(default='タイトル', max_length=60, verbose_name='タイトル'),
        ),
        migrations.AlterField(
            model_name='introcourse',
            name='order',
            field=models.PositiveSmallIntegerField(verbose_name='順番'),
        ),
    ]
