# Generated by Django 4.2.7 on 2023-12-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonL', '0010_remove_introcourse_name_introcourse_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='introcourse',
            name='name',
            field=models.CharField(default='題名', max_length=60, verbose_name='題名'),
        ),
    ]
