# Generated by Django 4.2.7 on 2023-12-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonL', '0011_introcourse_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introcourse',
            name='name',
            field=models.CharField(max_length=60, verbose_name='題名'),
        ),
        migrations.AlterField(
            model_name='introcourse',
            name='title',
            field=models.CharField(max_length=60, verbose_name='タイトル'),
        ),
    ]
