# Generated by Django 4.2.7 on 2023-12-13 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonL', '0013_remove_introcourse_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntroForeword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='タイトル')),
                ('major_section', models.PositiveSmallIntegerField(verbose_name='大区分')),
                ('minor_section', models.PositiveIntegerField(verbose_name='小区分')),
            ],
        ),
        migrations.AlterField(
            model_name='introcourse',
            name='text_type',
            field=models.CharField(blank=True, choices=[('heading', '見出し'), ('text', 'テキスト'), ('red', '赤枠'), ('yellow', '黄枠'), ('blue', '青枠'), ('green', '緑枠'), ('img', '画像')], max_length=20, verbose_name='タイプ'),
        ),
    ]
