# Generated by Django 4.2.7 on 2023-12-13 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pythonL', '0014_introforeword_alter_introcourse_text_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IntroForeword',
        ),
    ]
