# Generated by Django 4.2.7 on 2023-12-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonL', '0015_delete_introforeword'),
    ]

    operations = [
        migrations.AddField(
            model_name='basis',
            name='unit',
            field=models.PositiveIntegerField(default=1, verbose_name='大区分'),
        ),
        migrations.AlterField(
            model_name='basis',
            name='name',
            field=models.CharField(max_length=60, verbose_name='題名'),
        ),
        migrations.AlterField(
            model_name='basis',
            name='section',
            field=models.PositiveSmallIntegerField(verbose_name='小区分'),
        ),
    ]
