# Generated by Django 4.2.7 on 2023-12-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonL', '0016_basis_unit_alter_basis_name_alter_basis_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basis',
            name='name',
        ),
        migrations.AddField(
            model_name='basis',
            name='u_title',
            field=models.CharField(default='大枠タイトル', max_length=60, verbose_name='題名'),
        ),
        migrations.AlterField(
            model_name='basis',
            name='unit',
            field=models.PositiveIntegerField(verbose_name='大区分'),
        ),
    ]
