# Generated by Django 4.2.7 on 2023-12-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonL', '0017_remove_basis_name_basis_u_title_alter_basis_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='basis',
            name='q_key',
            field=models.BooleanField(default=False, verbose_name='フィルター用'),
        ),
        migrations.AlterField(
            model_name='basis',
            name='u_title',
            field=models.CharField(max_length=60, verbose_name='題名'),
        ),
    ]
