# Generated by Django 4.2.7 on 2023-12-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonL', '0018_basis_q_key_alter_basis_u_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basis',
            name='u_title',
        ),
        migrations.AddField(
            model_name='basis',
            name='major_h',
            field=models.CharField(blank=True, max_length=20, verbose_name='問題グループ'),
        ),
        migrations.AddField(
            model_name='basis',
            name='minor_h',
            field=models.CharField(blank=True, max_length=20, verbose_name='問題名'),
        ),
        migrations.AlterField(
            model_name='basis',
            name='title',
            field=models.CharField(max_length=60, verbose_name='問題内容'),
        ),
    ]
