# Generated by Django 4.2.7 on 2023-12-18 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonL', '0020_alter_basis_c_output_alter_basis_e_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basis',
            name='i_range',
            field=models.TextField(blank=True, verbose_name='範囲[]/gvc/'),
        ),
    ]
