# Generated by Django 4.2.7 on 2023-12-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonL', '0021_alter_basis_i_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='condition',
            field=models.TextField(blank=True, verbose_name='条件'),
        ),
        migrations.AddField(
            model_name='competition',
            name='expectation',
            field=models.TextField(blank=True, verbose_name='期待出力'),
        ),
        migrations.AddField(
            model_name='competition',
            name='input_format',
            field=models.TextField(blank=True, verbose_name='入力フォーマット'),
        ),
    ]
