# Generated by Django 4.2.7 on 2023-12-19 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonL', '0022_competition_condition_competition_expectation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='s_input',
            field=models.TextField(blank=True),
        ),
    ]
