# Generated by Django 4.2.7 on 2023-12-19 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonL', '0023_customuser_s_input'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='name',
        ),
        migrations.AddField(
            model_name='competition',
            name='title',
            field=models.CharField(default='name', max_length=60, verbose_name='問題名'),
        ),
    ]
