# Generated by Django 4.2.7 on 2023-12-19 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonL', '0024_remove_competition_name_competition_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='condition',
            field=models.TextField(verbose_name='条件'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='expectation',
            field=models.TextField(verbose_name='期待出力'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='input_format',
            field=models.TextField(verbose_name='入力フォーマット'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='title',
            field=models.CharField(max_length=60, verbose_name='問題名'),
        ),
    ]
