# Generated by Django 4.2.7 on 2023-12-22 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonL', '0025_alter_competition_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='condition',
            field=models.TextField(blank=True, verbose_name='条件'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='expectation',
            field=models.TextField(blank=True, verbose_name='期待出力'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='input_data',
            field=models.TextField(default='/separate/', verbose_name='入力データ'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='input_ex',
            field=models.TextField(default='/separate/', verbose_name='入力例'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='input_format',
            field=models.TextField(blank=True, verbose_name='入力フォーマット'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='output_data',
            field=models.TextField(default='/separate/', verbose_name='出力データ'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='output_ex',
            field=models.TextField(default='/separate/', verbose_name='出力例'),
        ),
    ]
