# Generated by Django 4.2.7 on 2023-12-27 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonL', '0026_alter_competition_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basis',
            name='g_range',
            field=models.TextField(blank=True, verbose_name='範囲の範囲'),
        ),
        migrations.AlterField(
            model_name='basis',
            name='c_output',
            field=models.TextField(blank=True, verbose_name='要求出力/Qend'),
        ),
        migrations.AlterField(
            model_name='basis',
            name='e_answer',
            field=models.TextField(blank=True, verbose_name='解答例/Qend'),
        ),
        migrations.AlterField(
            model_name='basis',
            name='q_data',
            field=models.TextField(blank=True, verbose_name='出題データ/Qend'),
        ),
    ]
