# Generated by Django 4.2.7 on 2023-12-27 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pythonL', '0027_basis_g_range_alter_basis_c_output_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='a_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='c_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='s_answer',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='s_explain',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='s_input',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='s_output',
        ),
    ]
