# Generated by Django 5.0 on 2023-12-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonL', '0028_remove_customuser_a_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quartet',
            name='choices',
        ),
        migrations.RemoveField(
            model_name='quartet',
            name='name',
        ),
        migrations.AddField(
            model_name='quartet',
            name='choices1',
            field=models.TextField(blank=True, verbose_name='選択肢1'),
        ),
        migrations.AddField(
            model_name='quartet',
            name='choices2',
            field=models.TextField(blank=True, verbose_name='選択肢2'),
        ),
        migrations.AddField(
            model_name='quartet',
            name='choices3',
            field=models.TextField(blank=True, verbose_name='選択肢3'),
        ),
        migrations.AddField(
            model_name='quartet',
            name='choices4',
            field=models.TextField(blank=True, verbose_name='選択肢4'),
        ),
        migrations.AddField(
            model_name='quartet',
            name='title',
            field=models.CharField(blank=True, max_length=60, verbose_name='問題名'),
        ),
        migrations.AlterField(
            model_name='quartet',
            name='question_code',
            field=models.TextField(blank=True, verbose_name='問題（コード）'),
        ),
    ]
