# Generated by Django 5.0 on 2023-12-30 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonL', '0029_remove_quartet_choices_remove_quartet_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quartet',
            name='unit',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='大区分'),
        ),
    ]
