# Generated by Django 5.0 on 2024-01-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonL', '0030_quartet_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quartet',
            name='question',
            field=models.TextField(default='以下のコードを実行した時の出力として正しいものを選択してください。', verbose_name='問題文'),
        ),
    ]
